config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'kitchens#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :kitchens do
    resources :bookings, only: [ :create]
  end

  resources :bookings, only: [:destroy] do
    member do
      patch 'decline'
      patch 'approve'
    end
    collection  do
      get 'confirm_booking'
    end
  end


  get "/dashboard", to: 'dashboards#show', as: :show_dashboard

  # patch "/bookings/:id/decline", to: "bookings#decline", as: :decline_booking
  # patch "/bookings/:id/approve", to: "bookings#approve", as: :approve_booking
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :kitchen

  validates :start_date, presence: true, on: :create
  validates :end_date, presence: true, on: :create
  validates :user_id, presence: true, on: :create
  validates :kitchen_id, presence: true, on: :create

  validate :start_must_be_today_or_after, :end_must_be_after_start_date, :user_must_not_be_owner, on: :create
  # scope :received_bookings, -> { .where('kitchen_id = ?', ) }

  def start_must_be_today_or_after
  	if start_date.present? && start_date < Date.today
  		errors.add(:start_date, "cannot be in the past")
  	end
  end

  def end_must_be_after_start_date
  	if end_date.present? && end_date <= start_date
  		errors.add(:end_date, "must be after the start date")
  	end
  end

  def user_must_not_be_owner
  	if self.kitchen.user == self.user
  		errors.add(:user_id, "you cannot book your own kitchen!")
  	end
  end

  def approved?
    self.status == "approved"
  end

  def declined?
    self.status == "declined"
  end
end

app/models/kitchen.rb
class Kitchen < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  mount_uploader :picture, PictureUploader

  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :users, through: :bookings

  validates :title, presence: true
  validates :address, presence: true
  validates :price, presence: true
  validates :user_id, presence: true

  def booked_before?(user)
  	self.users.include?(user)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :kitchens
  has_many :bookings
  # has_many :bookings, through: :kitchens

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def new
    @kitchen = Kitchen.find(params[:kitchen_id])
    @booking = Booking.new
  end

  def create
    @kitchen = Kitchen.find(params[:kitchen_id])
    @booking = Booking.new(booking_params)
    @booking.kitchen = @kitchen
    @booking.user = current_user
    @booking.total_price = calculate_total_price
    if @booking.valid?
      respond_to do |format|
        format.html
        format.js
      end
    else
      respond_to do |format|
        format.html
        format.js
      end
    end
  end

  def confirm_booking
    @booking = Booking.new(booking_params)
    @kitchen = Kitchen.find(params[:booking][:kitchen_id])
    @booking.kitchen = @kitchen
    @booking.user = current_user
    @booking.total_price = calculate_total_price
    @booking.save
    redirect_to kitchen_path(@booking.kitchen)
  end

  def approve
    @booking = Booking.find(params[:id])
    @booking.status = "approved"
    if @booking.save
      respond_to do |format|
        format.html {redirect_to show_dashboard_path}
        format.js { render :update }
      end
    end
  end

  def decline
    @booking = Booking.find(params[:id])
    @booking.status = "declined"
    if @booking.save
      respond_to do |format|
        format.html {redirect_to show_dashboard_path}
        format.js { render :update }
      end
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end

  def calculate_total_price
    (@booking.end_date - @booking.start_date) / 3_600 / 24 * @kitchen.price
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
  	@user = current_user
  	@bookings_sent = Booking.where(user: @user) #the bookings I have made to other kicthens
  	@kitchens = Kitchen.where(user: @user) #the kitchens I own
  	@bookings_received = @kitchens.map { |kitchen| kitchen.bookings }.flatten
	end	
end

app/controllers/kitchens_controller.rb
class KitchensController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_kitchen, only: [:show, :edit, :update, :destroy]

  def index
    # @kitchens = Kitchen.all
    @kitchens = Kitchen.where.not(latitude: nil, longitude: nil)
    @hash = Gmaps4rails.build_markers(@kitchens) do |kitchen, marker|
      marker.lat kitchen.latitude
      marker.lng kitchen.longitude
      marker.infowindow render_to_string(partial: "/kitchens/map_box", locals: { kitchen: kitchen })
    end
  end

  def new
    @kitchen = Kitchen.new
  end

  def create
    @kitchen = Kitchen.new(kitchen_params)
    @kitchen.user_id = current_user.id
    if @kitchen.save
      redirect_to kitchen_path(@kitchen)
    else
      render :new
    end
  end

  def show
    @booking = Booking.new
  end

  def edit
  end

  def update
    @kitchen.update(kitchen_params)
    if @kitchen.save
      redirect_to kitchen_path(@kitchen)
    else
      render :edit
    end
  end

  def destroy
    @kitchen.destroy
    redirect_to kitchens_path
  end

  private

  def set_kitchen
    @kitchen = Kitchen.find(params[:id])
  end

  def kitchen_params
    params.require(:kitchen).permit(:title, :description, :address, :picture, :price)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_bookingcontent.html.erb
<div class="message-body">

  <div class="message-body-guest">
    <p>Host: <%= booking.user.email %></p>
  </div>

  <div class="message-body-title">
    <p>Kitchen: <%= booking.kitchen.title %></p>
  </div>

  <div class="message-body-date">
    <div class="message-body-date-start">
      <p>From: <%= booking.start_date.strftime('%b %d, %Y') %></p>
    </div>

    <div class="message-body-date-end">
      <p>To: <%= booking.end_date.strftime('%b %d, %Y') %></p>
    </div>
  </div>

</div>

<div class="message-price">
  <p>$<%= booking.total_price %></p>
</div>
<div class="message-status">
  <p><%= booking.status %></p>
</div>


<div class="dropdown" id="dropdown-dashboard">
  <% if booking.approved? %>
  <%= link_to "Decline", decline_booking_path(booking), method: :patch, class: "btn btn-danger", remote: true %>
  <% else %>
  <%= link_to "Approve", approve_booking_path(booking), method: :patch, class: "btn btn-success", remote: true  %>
  <% end %>

</div>

app/views/bookings/_form.html.erb
<div id="booking-form">
  <%= simple_form_for([@kitchen, @booking], remote: true) do |f| %>
    <%= f.error :user_id %>
    <%= f.input :start_date, as: :date, start_year: Date.today.year, end_year: Date.today.year + 2, start_month: Date.today.month, start_day: Date.today.mday, order: [:day, :month, :year]%>
    <%= f.input :end_date, default: Date.today + 1, as: :date, start_year: Date.today.year, end_year: Date.today.year + 2, start_month: Date.today.month , order: [:day, :month, :year]%>
    <br>
    <% if user_signed_in? %>
		  <%= f.submit class: "btn btn-primary" %>
    <% else %>
      <p>You must <%= link_to "login", new_user_session_path %> to request a booking</p>
    <% end %>
  <% end %>
</div>

<!-- <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Please confirm your booking</h4>
      </div>
      <div class="modal-body">
       <p>You are about to book the kitchen starting <= @booking.start_date %> for <= @booking.end_date - @booking.end_date %> days</p>
        <p>The total cost of this booking will be <= @booking.total_price %>$</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-success" data-dismiss="modal">Confirm booking</button>
      </div>
    </div>
  </div>
</div> -->

app/views/bookings/_modal.html.erb
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Please confirm your booking</h4>
      </div>
      <div class="modal-body">
       <p>You are about to book <%= booking.kitchen.title  %></p>
       <p><i class="far fa-calendar-alt"></i>  starting <%= booking.start_date.strftime("%A, %b %d (%Y)") %></p>
       <p><i class="far fa-clock"></i>  for <%= pluralize(((booking.end_date - booking.start_date)/3600/24).round, "day") %></p>
        <p><strong>The total cost of this booking will be $ <%= booking.total_price %></strong></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <%= link_to  'Confirm booking', {:controller => "bookings", :action => "confirm_booking", :booking => booking.attributes }, class: "btn btn-success" %>

      </div>
    </div>
  </div>
</div>

app/views/bookings/_show.html.erb
<div class="message-body">

  <div class="message-body-title">
    <%= link_to kitchen_path(booking.kitchen) do %>
      <p><strong>Kitchen: <%= booking.kitchen.title %></strong></p>
    <% end %>
  </div>

  <div class="message-body-guest">
    <p>Guest: <%= booking.user.email %></p>
  </div>

  <div class="message-body-date">
    <div class="message-body-date-start">
      <p>From: <%= booking.start_date.strftime('%b %d, %Y') %></p>
    </div>

    <div class="message-body-date-end">
      <p>To: <%= booking.end_date.strftime('%b %d, %Y') %></p>
    </div>
  </div>

</div>

<div class="message-price">
  <p>$<%= booking.total_price %></p>
</div>

<% if booking.status == "approved" %>
  <div class="message-status for-me" id="approved">
    <i class="fas fa-check"></i>
    <p><%= booking.status %></p>
  </div>
<% elsif booking.status == "declined" %>
  <div class="message-status for-me" id="declined">
    <i class="fas fa-times"></i>
    <p><%= booking.status %></p>
  </div>
<% else %>
  <div class="message-status for-me" id="pending">
    <i class="fas fa-question"></i>
    <p><%= booking.status %></p>
  </div>
<% end %>


<div class="dropdown" id="booking-decision">
  <% if booking.approved? %>
    <%= link_to "Cancel", decline_booking_path(booking), method: :patch, class: "btn btn-cancel btn-msg", remote: true %>
  <% elsif booking.declined? %>
    <p id="decline-message">You have declined this request.</p>
  <% else %>
    <%= link_to "Approve", approve_booking_path(booking), method: :patch, class: "btn navbar-button-green btn-msg", remote: true  %>
    <%= link_to "Decline", decline_booking_path(booking), method: :patch, class: "btn btn-cancel btn-msg", remote: true %>
  <% end %>

</div>

app/views/bookings/create.js.erb
function renderModal(modalHtml) {
	const modal = document.getElementById('confirm-booking');
	modal.innerHTML = modalHtml
}

function refreshForm(innerHTML) {
  const bookingForm = document.getElementById('booking-form');
  bookingForm.innerHTML = innerHTML;
}

<% if @booking.errors.any? %>
  refreshForm('<%= j render "bookings/form", kitchen: @kitchen, booking: @booking %>');
<% else %>
	 renderModal('<%= j render "bookings/modal", booking: @booking %>');
	$('#myModal').modal();
  refreshForm('<%= j render "bookings/form", kitchen: @kitchen, booking: Booking.new %>');
<% end %>

app/views/bookings/update.js.erb
function updateBooking(bookingHtml) {
  const booking = document.querySelector("[data-booking-id='<%= @booking.id %>']")
  booking.innerHTML = bookingHtml
};

updateBooking("<%= j render 'show', booking: @booking %>");

app/views/dashboards/_bookingforme.html.erb
<ul class="inbox">
  <% @bookings_received.each do |booking| %>
    <li class="message" data-booking-id="<%= booking.id %>">
      <%= render 'bookings/show', booking: booking %>
    </li>
  <% end %>
</ul>

app/views/dashboards/_bookingfromme.html.erb
<ul class="inbox">
  <% @bookings_sent.each do |booking| %>
    <li class="message">

      <div class="message-body">

        <div class="message-body-title">
          <%= link_to kitchen_path(booking.kitchen) do %>
          <p><strong>Kitchen: <%= booking.kitchen.title %></strong></p>
          <% end %>
        </div>

        <div class="message-body-host">
          <p>Host: <%= booking.kitchen.user.email %></p>
        </div>

        <div class="message-body-date">
          <div class="message-body-date-start">
            <p>From: <%= booking.start_date.strftime('%b %d, %Y') %></p>
          </div>

          <div class="message-body-date-end">
            <p>To: <%= booking.end_date.strftime('%b %d, %Y') %></p>
          </div>
        </div>

      </div>

      <div class="message-price">
        <p>$<%= booking.total_price %></p>
      </div>

      <% if booking.status == "approved" %>
        <div class="message-status" id="approved">
          <p><%= booking.status %></p>
        </div>
      <% elsif booking.status == "declined" %>
        <div class="message-status" id="declined">
          <p><%= booking.status %></p>
        </div>
      <% else %>
        <div class="message-status" id="pending">
          <p><%= booking.status %></p>
        </div>
      <% end %>

    </li>
  <% end %>
</ul>

app/views/dashboards/_mykitch.html.erb
<div class="row">
  <% @kitchens.each do |kitchen| %>
    <div class="col-xs-12 col-sm-6 col-md-4">
      <div class="card">

        <%= link_to kitchen_path(kitchen) do %>
          <div class="card-image" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= image_path kitchen.picture %>')">
          </div>
        <% end %>

        <div class="body">
          <div class="card-title">
            <%= link_to kitchen.title, kitchen_path(kitchen) %>
          </div>
          <div class="card-price">
            <p>From $<%= kitchen.price %>,- per day</p>
          </div>
        </div>

      </div>
    </div>
  <% end %>

</div>

app/views/dashboards/show.html.erb
<div class="container-dashboard">
  <div class="container">

  	<h2>My Dashboard</h2>

    <ul class="nav nav-tabs">
      <li class="active"><a data-toggle="tab" href="#home">My Bookings</a></li>
      <li><a data-toggle="tab" href="#menu1">My Kitchens</a></li>
    </ul>

    <div class="tab-content">

    <div id="home" class="tab-pane fade in active">
    	<h3>Bookings I have requested</h3>
      <% if @bookings_sent.empty? %>
        <%= "You have not booked any kitchens." %>
      <% else %>
        <%= render 'bookingfromme' %>
      <% end %>
    </div>

    <div id="menu1" class="tab-pane fade">
      <h3>My Kitchens</h3>
      <% if @kitchens.empty? %>
        <%= "You don't have any kitchens." %>
      <% else %>
        <%= render 'mykitch' %>
      <% end %>

    	<h3>Bookings for my Kitchens</h3>
      <% if @bookings_received.empty? %>
        <%= "None of your kitchens is booked." %>
      <% else %>
        <%= render 'bookingforme' %>
      <% end %>
    </div>

  </div>
</div>

app/views/kitchens/_form.html.erb
<%= simple_form_for(@kitchen) do |f| %>
  <%= f.input :title, placeholder: "eg. Sébastien's Sun Soaked Kitchen" %>
  <%= f.input :description, placeholder: 'eg. Island kitchen in the center of Paris'%>
  <%= f.input :address, placeholder: 'eg. 16 Villa Gaudelet, 75011 Paris, France' %>
  <%= f.input :price, placeholder: '75'%>
  <%= f.input :picture %>
  <%= f.input :picture_cache, as: :hidden %>
  <%= f.button :submit, class: "btn btn-primary margin-bottom margin-top" %>
<% end %>

app/views/kitchens/_map_box.html.erb
<div class="card-google">
  <%= link_to kitchen_path(kitchen) do %>
  <div class="card-image-google">
    <%= cl_image_tag kitchen.picture, width: "200px" %>
  </div>
  <div class="body-google">
    <div class="card-title-google">
      <%= kitchen.title %>
    </div>
    <div class="card-price-google">
      From $<%= kitchen.price %> per day
    </div>
    <% end %>
  </div>
</div>

app/views/kitchens/edit.html.erb
<h1>Edit kitchen</h1>
<%= render 'form' %>

app/views/kitchens/index.html.erb
<div class="main-container">
  <div class="container">
    <div class="row">
      <div class="main-intro">
        <h4>Bake Like Jamie O.</h4>
        <p>Book a kitchen in cities around the world</p>
      </div>
      <% @kitchens.each do |kitchen| %>
        <div class="col-xs-12 col-md-6">
          <div class="card">
            <%= link_to kitchen_path(kitchen) do %>
            <div class="card-image" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= image_path kitchen.picture %>')">
            </div>
            <% end %>
            <div class="body">
              <%= link_to kitchen_path(kitchen) do %>
              <div class="card-title">
                <%= kitchen.title %>
              </div>
              <div class="card-price">
                <p>From $<%= kitchen.price %> per day</p>
              </div>
              <% end %>
            </div>
            <i class="fas fa-heart card-icon"></i>
          </div>
          <a class="card-link" href="#"></a>
        </div>
      <% end %>
    </div>
  </div>
  <div id="map"></div>
</div>

<script>
document.querySelectorAll(".card-icon").forEach((icon) => {
  icon.addEventListener("click", (event) => {
    event.currentTarget.classList.toggle("heart-blue");
  });
});
</script>
<!-- id="card-icon" -->
<!-- <script>
  !!!!!onclick="myFunction()" # add after card-icon

  function myFunction() {
    var colorIcon = document.getElementById("card-icon").style.color;
    if (colorIcon == "black") {
      document.getElementById("card-icon").style.color = "#30C2FF";
    } else {
      document.getElementById("card-icon").style.color = "black";
    }
  }
</script> -->

<!-- Gmaps js: building map with markers -->
<% content_for(:after_js) do %>
  <script type="text/javascript">
    var handler = Gmaps.build('Google');
    var styles =   [{"featureType":"water","elementType":"geometry","stylers":[{"color":"#e9e9e9"},{"lightness":17}]},{"featureType":"landscape","elementType":"geometry","stylers":[{"color":"#f5f5f5"},{"lightness":20}]},{"featureType":"road.highway","elementType":"geometry.fill","stylers":[{"color":"#ffffff"},{"lightness":17}]},{"featureType":"road.highway","elementType":"geometry.stroke","stylers":[{"color":"#ffffff"},{"lightness":29},{"weight":0.2}]},{"featureType":"road.arterial","elementType":"geometry","stylers":[{"color":"#ffffff"},{"lightness":18}]},{"featureType":"road.local","elementType":"geometry","stylers":[{"color":"#ffffff"},{"lightness":16}]},{"featureType":"poi","elementType":"geometry","stylers":[{"color":"#f5f5f5"},{"lightness":21}]},{"featureType":"poi.park","elementType":"geometry","stylers":[{"color":"#dedede"},{"lightness":21}]},{"elementType":"labels.text.stroke","stylers":[{"visibility":"on"},{"color":"#ffffff"},{"lightness":16}]},{"elementType":"labels.text.fill","stylers":[{"saturation":36},{"color":"#333333"},{"lightness":40}]},{"elementType":"labels.icon","stylers":[{"visibility":"off"}]},{"featureType":"transit","elementType":"geometry","stylers":[{"color":"#f2f2f2"},{"lightness":19}]},{"featureType":"administrative","elementType":"geometry.fill","stylers":[{"color":"#fefefe"},{"lightness":20}]},{"featureType":"administrative","elementType":"geometry.stroke","stylers":[{"color":"#fefefe"},{"lightness":17},{"weight":1.2}]}];
    handler.buildMap({
      provider: {
        styles: styles
      },
      internal: { id: 'map' } }, function(){
      markers = handler.addMarkers(<%= raw @hash.to_json %>,
        );

      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
      if (markers.length == 0) {
        handler.getMap().setZoom(2);
      } else if (markers.length == 1) {
        handler.getMap().setZoom(14);
      }
    });
  </script>
<% end %>

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

app/views/kitchens/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h2>Add Kitchen</h2>
      <%= render 'form' %>
      <%= link_to 'back to more kitchens', kitchens_path %>
    </div>
  </div>
</div>

app/views/kitchens/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
         url('<%= cl_image_path @kitchen.picture, crop: :fill %>')">
</div>
<div>
<div class="container details-show-kitchen">
		<div class="info">
			<h1><%= @kitchen.title %></h1>
			<p><%= @kitchen.description %></p>
			<p><em>Price: $<%= @kitchen.price %> per day</em></p>

			<% if @kitchen.booked_before?(current_user) %>
				<p>You already booked this kitchen. Please check your <%= link_to "dashboard", show_dashboard_path %>.</p>
			<% end %>

		</div>
		<div class="book-box">
			<h4>Book this kitchen!</h4>
			<%= render 'bookings/form'  %>
		</div>
</div>
<div class="container details-show-kitchen">
	<p><%= link_to "back to more kitchens", kitchens_path, class: "margin-left-show" %></p>
</div>

<div id="confirm-booking"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Use My Kitch</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>

    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>
    <%#= javascript_pack_tag 'application' %>
    <%= javascript_include_tag 'application' %>
    <%= yield(:after_js) %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <%= link_to " " do %>
      <i class="fab fa-facebook"></i>
    <% end %>
    <%= link_to " " do %>
      <i class="fab fa-twitter"></i>
    <% end %>
     <%= link_to " " do %>
      <i class="fab fa-instagram"></i>
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Add Kitchen", new_kitchen_path, class: "navbar-button-green" %>
      <%= link_to "Dashboard", show_dashboard_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "boris.jpg", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to "Add Kitchen", new_kitchen_path %></li>
        <li><%= link_to "Dashboard", show_dashboard_path %></li>
        <li><%= link_to "Profile" %></li>
        <li><%= link_to "Settings" %></li>
        <li><%= link_to "Log Out" %></li>
      </ul>
    </div>
  </div>
</div>